// User Errors
exports.MISSING_USER_INFO = 400
exports.USER_ALREADY_EXISTS = 401
exports.CANNOT_FIND_USER = 402
exports.CANNOT_FIND_AND_DELETE_USER = 403
exports.CANNOT_FIND_AND_UPDATE_USER = 404

// Doctor Errors
exports.MISSING_REQUIRED_DOCTOR_INFO = 405
exports.DOCTOR_ALREADY_EXISTS = 406
exports.CANNOT_FIND_DOCTOR = 407
exports.CANNOT_FIND_AND_DELETE_DOCTOR = 408
exports.CANNOT_FIND_AND_UPDATE_DOCTOR = 409

// Appointment Errors
exports.MISSING_REQUIRED_APPOINTMENT_INFO = 410
exports.APPOINTMENT_ALREADY_EXISTS = 411
exports.CANNOT_FIND_APPOINTMENT = 412
exports.CANNOT_FIND_AND_DELETE_APPOINTMENT = 413
exports.CANNOT_FIND_AND_UPDATE_APPOINTMENT = 414

// Room Errors
exports.MISSING_REQUIRED_ROOM_INFO = 415
exports.ROOM_ALREADY_EXISTS = 416
exports.CANNOT_FIND_ROOM = 417
exports.CANNOT_FIND_AND_DELETE_ROOM= 418
exports.CANNOT_FIND_AND_UPDATE_ROOM = 419

// Clinic Errors
exports.MISSING_REQUIRED_CLINIC_INFO = 420
exports.CLINIC_ALREADY_EXISTS = 421
exports.CANNOT_FIND_CLINIC = 422
exports.CANNOT_FIND_AND_DELETE_CLINIC = 423
exports.CANNOT_FIND_AND_UPDATE_CLINIC = 424

// Schedule Errors
exports.SCHEDULE_ALREADY_EXISTS = 425
exports.CANNOT_FIND_SCHEDULE = 426
exports.CANNOT_FIND_AND_DELETE_SCHEDULE = 427
exports.CANNOT_FIND_AND_UPDATE_SCHEDULE = 428

// Patient Errors
exports.MISSING_REQUIRED_PATIENT_INFO = 429
exports.PATIENT_ALREADY_EXISTS = 430
exports.CANNOT_FIND_PATIENT = 431
exports.CANNOT_FIND_AND_DELETE_PATIENT = 432
exports.CANNOT_FIND_AND_UPDATE_PATIENT = 433